//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanilvarKanji.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanilvarKanji.Client.Resources.App.ru-RU", typeof(App_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись успешно зарегистрирована!.
        /// </summary>
        internal static string AccountRegistered {
            get {
                return ResourceManager.GetString("AccountRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый иероглиф.
        /// </summary>
        internal static string AddNewChar {
            get {
                return ResourceManager.GetString("AddNewChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую коллекцию.
        /// </summary>
        internal static string AddNewCollection {
            get {
                return ResourceManager.GetString("AddNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админинстратор.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАЗАД.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер холста.
        /// </summary>
        internal static string CanvasSize {
            get {
                return ResourceManager.GetString("CanvasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная информация иероглифа.
        /// </summary>
        internal static string CharacterBasicDetails {
            get {
                return ResourceManager.GetString("CharacterBasicDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация об иероглифа, общая для всех языков.
        /// </summary>
        internal static string CharacterBasicDetailsText {
            get {
                return ResourceManager.GetString("CharacterBasicDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск иероглифа по значению, чтению и определению....
        /// </summary>
        internal static string CharacterSearchPlaceholder {
            get {
                return ResourceManager.GetString("CharacterSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип иероглифа.
        /// </summary>
        internal static string CharacterType {
            get {
                return ResourceManager.GetString("CharacterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция.
        /// </summary>
        internal static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название коллекции.
        /// </summary>
        internal static string CollectionName {
            get {
                return ResourceManager.GetString("CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить Email.
        /// </summary>
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определение.
        /// </summary>
        internal static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Словарь.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите слово по переводу, кане или кандзи....
        /// </summary>
        internal static string DictionaryPlaceholder {
            get {
                return ResourceManager.GetString("DictionaryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы помните это?.
        /// </summary>
        internal static string DoYouRemember {
            get {
                return ResourceManager.GetString("DoYouRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите определение иероглифа.
        /// </summary>
        internal static string EnterCharacterDefinition {
            get {
                return ResourceManager.GetString("EnterCharacterDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извлекатель текста.
        /// </summary>
        internal static string ExtractText {
            get {
                return ResourceManager.GetString("ExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извлечь текст из.
        /// </summary>
        internal static string ExtractTextFrom {
            get {
                return ResourceManager.GetString("ExtractTextFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извлечеть японский текст из изображения.
        /// </summary>
        internal static string ExtractTextTitle {
            get {
                return ResourceManager.GetString("ExtractTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить.
        /// </summary>
        internal static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бэк.
        /// </summary>
        internal static string FlashcardBack {
            get {
                return ResourceManager.GetString("FlashcardBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Флэш-карты.
        /// </summary>
        internal static string Flashcards {
            get {
                return ResourceManager.GetString("Flashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К примеру.
        /// </summary>
        internal static string ForExample {
            get {
                return ResourceManager.GetString("ForExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕ ПОМНЮ.
        /// </summary>
        internal static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фронт.
        /// </summary>
        internal static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сгенерировать учетные данные.
        /// </summary>
        internal static string GenCreds {
            get {
                return ResourceManager.GetString("GenCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к ревью?.
        /// </summary>
        internal static string GoToReview {
            get {
                return ResourceManager.GetString("GoToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горизонтальный.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите валидную электронную почту.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я ПОМНЮ ЭТО В ИДЕАЛЕ.
        /// </summary>
        internal static string IRememberItPerfectly {
            get {
                return ResourceManager.GetString("IRememberItPerfectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Японское написание.
        /// </summary>
        internal static string JapaneseWriting {
            get {
                return ResourceManager.GetString("JapaneseWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандзи.
        /// </summary>
        internal static string Kanji {
            get {
                return ResourceManager.GetString("Kanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно вошли в аккаунт!.
        /// </summary>
        internal static string LoggenIn {
            get {
                return ResourceManager.GetString("LoggenIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти в свой аккаунт.
        /// </summary>
        internal static string LogInToYourAccount {
            get {
                return ResourceManager.GetString("LogInToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выучено.
        /// </summary>
        internal static string Memorized {
            get {
                return ResourceManager.GetString("Memorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мое изучение.
        /// </summary>
        internal static string MyLearning {
            get {
                return ResourceManager.GetString("MyLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наруто.
        /// </summary>
        internal static string Naruto {
            get {
                return ResourceManager.GetString("Naruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только начали изучать японский? Попробуйте игру.
        /// </summary>
        internal static string NewToJapanese1 {
            get {
                return ResourceManager.GetString("NewToJapanese1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - это увлекательное приключение для освоения основ японского!.
        /// </summary>
        internal static string NewToJapanese2 {
            get {
                return ResourceManager.GetString("NewToJapanese2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIHONGO КВЕСТ.
        /// </summary>
        internal static string NihongoQuest {
            get {
                return ResourceManager.GetString("NihongoQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иероглиф должен содержать хотя бы одно значение.
        /// </summary>
        internal static string NoMeanings {
            get {
                return ResourceManager.GetString("NoMeanings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иероглиф должен содержать хотя бы одну мнемонику.
        /// </summary>
        internal static string NoMnemonics {
            get {
                return ResourceManager.GetString("NoMnemonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите значение.
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите определение.
        /// </summary>
        internal static string NotEmptyCharDef {
            get {
                return ResourceManager.GetString("NotEmptyCharDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите количество штрихов.
        /// </summary>
        internal static string NotEmptyStrokeCount {
            get {
                return ResourceManager.GetString("NotEmptyStrokeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, на этом адресе ничего не найдено..
        /// </summary>
        internal static string NothingAtAddress {
            get {
                return ResourceManager.GetString("NothingAtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТКРЫТЬ ИЗОБРАЖЕНИЕ.
        /// </summary>
        internal static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повтор пароля.
        /// </summary>
        internal static string PasswordRepeat {
            get {
                return ResourceManager.GetString("PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать.
        /// </summary>
        internal static string PasswordRepeatMismath {
            get {
                return ResourceManager.GetString("PasswordRepeatMismath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы одну цифру.
        /// </summary>
        internal static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы одну строчную латинскую букву.
        /// </summary>
        internal static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы один специальный символ.
        /// </summary>
        internal static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы одну заглавую латинскую букву.
        /// </summary>
        internal static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль слишком короткий, должно быть хотя бы.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простой пользователь.
        /// </summary>
        internal static string PlainUser {
            get {
                return ResourceManager.GetString("PlainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Радикал.
        /// </summary>
        internal static string Radical {
            get {
                return ResourceManager.GetString("Radical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегестрироваться.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегестрировать новый аккаунт.
        /// </summary>
        internal static string RegisterNewAccount {
            get {
                return ResourceManager.GetString("RegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации.
        /// </summary>
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОМНЮ.
        /// </summary>
        internal static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить последний.
        /// </summary>
        internal static string RemoveLast {
            get {
                return ResourceManager.GetString("RemoveLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ревью.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество штрихов.
        /// </summary>
        internal static string StrokeCount {
            get {
                return ResourceManager.GetString("StrokeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обучение окончено.
        /// </summary>
        internal static string StudyIsComplete {
            get {
                return ResourceManager.GetString("StudyIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супер-администратор.
        /// </summary>
        internal static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раз подряд.
        /// </summary>
        internal static string TimesInARow {
            get {
                return ResourceManager.GetString("TimesInARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть.
        /// </summary>
        internal static string ToView {
            get {
                return ResourceManager.GetString("ToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не может быть больше чем .
        /// </summary>
        internal static string ValueTooLong {
            get {
                return ResourceManager.GetString("ValueTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение должно быть больше чем .
        /// </summary>
        internal static string ValueTooSmall {
            get {
                return ResourceManager.GetString("ValueTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вертикальный.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какое кунное чтение у .
        /// </summary>
        internal static string WhatIsKunyomiFor {
            get {
                return ResourceManager.GetString("WhatIsKunyomiFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какое значение у .
        /// </summary>
        internal static string WhatIsMeaningFor {
            get {
                return ResourceManager.GetString("WhatIsMeaningFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какое онное чтение у .
        /// </summary>
        internal static string WhatIsOnyomiFor {
            get {
                return ResourceManager.GetString("WhatIsOnyomiFor", resourceCulture);
            }
        }
    }
}
