//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanilvarKanji.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanilvarKanji.Client.Resources.App.en-US", typeof(App_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully registered!.
        /// </summary>
        internal static string AccountRegistered {
            get {
                return ResourceManager.GetString("AccountRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Character.
        /// </summary>
        internal static string AddNewChar {
            get {
                return ResourceManager.GetString("AddNewChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Collection.
        /// </summary>
        internal static string AddNewCollection {
            get {
                return ResourceManager.GetString("AddNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Size.
        /// </summary>
        internal static string CanvasSize {
            get {
                return ResourceManager.GetString("CanvasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Basic Details.
        /// </summary>
        internal static string CharacterBasicDetails {
            get {
                return ResourceManager.GetString("CharacterBasicDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character information common for all lanugages.
        /// </summary>
        internal static string CharacterBasicDetailsText {
            get {
                return ResourceManager.GetString("CharacterBasicDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Type.
        /// </summary>
        internal static string CharacterType {
            get {
                return ResourceManager.GetString("CharacterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Name.
        /// </summary>
        internal static string CollectionName {
            get {
                return ResourceManager.GetString("CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You remember this?.
        /// </summary>
        internal static string DoYouRemember {
            get {
                return ResourceManager.GetString("DoYouRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter character definition.
        /// </summary>
        internal static string EnterCharacterDefinition {
            get {
                return ResourceManager.GetString("EnterCharacterDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Extractor.
        /// </summary>
        internal static string ExtractText {
            get {
                return ResourceManager.GetString("ExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text From.
        /// </summary>
        internal static string ExtractTextFrom {
            get {
                return ResourceManager.GetString("ExtractTextFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Japanese Text From Image.
        /// </summary>
        internal static string ExtractTextTitle {
            get {
                return ResourceManager.GetString("ExtractTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string FlashcardBack {
            get {
                return ResourceManager.GetString("FlashcardBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcards.
        /// </summary>
        internal static string Flashcards {
            get {
                return ResourceManager.GetString("Flashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example.
        /// </summary>
        internal static string ForExample {
            get {
                return ResourceManager.GetString("ForExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT.
        /// </summary>
        internal static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Credentials.
        /// </summary>
        internal static string GenCreds {
            get {
                return ResourceManager.GetString("GenCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the review?.
        /// </summary>
        internal static string GoToReview {
            get {
                return ResourceManager.GetString("GoToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I REMEMBER IT PERFECTLY.
        /// </summary>
        internal static string IRememberItPerfectly {
            get {
                return ResourceManager.GetString("IRememberItPerfectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanji.
        /// </summary>
        internal static string Kanji {
            get {
                return ResourceManager.GetString("Kanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged into your account!.
        /// </summary>
        internal static string LoggenIn {
            get {
                return ResourceManager.GetString("LoggenIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to your account.
        /// </summary>
        internal static string LogInToYourAccount {
            get {
                return ResourceManager.GetString("LogInToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memorized.
        /// </summary>
        internal static string Memorized {
            get {
                return ResourceManager.GetString("Memorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Learning.
        /// </summary>
        internal static string MyLearning {
            get {
                return ResourceManager.GetString("MyLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NARUTO.
        /// </summary>
        internal static string Naruto {
            get {
                return ResourceManager.GetString("Naruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to learning Japanese? Try.
        /// </summary>
        internal static string NewToJapanese1 {
            get {
                return ResourceManager.GetString("NewToJapanese1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an engaging adventure to master the basics of Japanese!.
        /// </summary>
        internal static string NewToJapanese2 {
            get {
                return ResourceManager.GetString("NewToJapanese2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIHONGO QUEST,.
        /// </summary>
        internal static string NihongoQuest {
            get {
                return ResourceManager.GetString("NihongoQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character should contain at least one meaning.
        /// </summary>
        internal static string NoMeanings {
            get {
                return ResourceManager.GetString("NoMeanings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character should contain at least one mnemonic.
        /// </summary>
        internal static string NoMnemonics {
            get {
                return ResourceManager.GetString("NoMnemonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value.
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a definition.
        /// </summary>
        internal static string NotEmptyCharDef {
            get {
                return ResourceManager.GetString("NotEmptyCharDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter stroke count.
        /// </summary>
        internal static string NotEmptyStrokeCount {
            get {
                return ResourceManager.GetString("NotEmptyStrokeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        internal static string NothingAtAddress {
            get {
                return ResourceManager.GetString("NothingAtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN IMAGE.
        /// </summary>
        internal static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the password.
        /// </summary>
        internal static string PasswordRepeat {
            get {
                return ResourceManager.GetString("PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should be equal.
        /// </summary>
        internal static string PasswordRepeatMismath {
            get {
                return ResourceManager.GetString("PasswordRepeatMismath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        internal static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one lowercase (&apos;a&apos;-&apos;z&apos;).
        /// </summary>
        internal static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one non alphanumeric character.
        /// </summary>
        internal static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;).
        /// </summary>
        internal static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short, it should be at least.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain User.
        /// </summary>
        internal static string PlainUser {
            get {
                return ResourceManager.GetString("PlainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radical.
        /// </summary>
        internal static string Radical {
            get {
                return ResourceManager.GetString("Radical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New Account.
        /// </summary>
        internal static string RegisterNewAccount {
            get {
                return ResourceManager.GetString("RegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMEMBER.
        /// </summary>
        internal static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Last.
        /// </summary>
        internal static string RemoveLast {
            get {
                return ResourceManager.GetString("RemoveLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke Number.
        /// </summary>
        internal static string StrokeCount {
            get {
                return ResourceManager.GetString("StrokeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study is complete.
        /// </summary>
        internal static string StudyIsComplete {
            get {
                return ResourceManager.GetString("StudyIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        internal static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times in a row.
        /// </summary>
        internal static string TimesInARow {
            get {
                return ResourceManager.GetString("TimesInARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ToView {
            get {
                return ResourceManager.GetString("ToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not exceed .
        /// </summary>
        internal static string ValueTooLong {
            get {
                return ResourceManager.GetString("ValueTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than .
        /// </summary>
        internal static string ValueTooSmall {
            get {
                return ResourceManager.GetString("ValueTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the kun reading of .
        /// </summary>
        internal static string WhatIsKunyomiFor {
            get {
                return ResourceManager.GetString("WhatIsKunyomiFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the meaning of .
        /// </summary>
        internal static string WhatIsMeaningFor {
            get {
                return ResourceManager.GetString("WhatIsMeaningFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the on reading of .
        /// </summary>
        internal static string WhatIsOnyomiFor {
            get {
                return ResourceManager.GetString("WhatIsOnyomiFor", resourceCulture);
            }
        }
    }
}
