//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanilvarKanji.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanilvarKanji.Client.Resources.App.en-US", typeof(App_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the review?.
        /// </summary>
        internal static string GoToReview {
            get {
                return ResourceManager.GetString("GoToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanji.
        /// </summary>
        internal static string Kanji {
            get {
                return ResourceManager.GetString("Kanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NARUTO.
        /// </summary>
        internal static string Naruto {
            get {
                return ResourceManager.GetString("Naruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character should contain at least one meaning.
        /// </summary>
        internal static string NoMeanings {
            get {
                return ResourceManager.GetString("NoMeanings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character should contain at least one mnemonic.
        /// </summary>
        internal static string NoMnemonics {
            get {
                return ResourceManager.GetString("NoMnemonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value.
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a definition.
        /// </summary>
        internal static string NotEmptyCharDef {
            get {
                return ResourceManager.GetString("NotEmptyCharDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter stroke count.
        /// </summary>
        internal static string NotEmptyStrokeCount {
            get {
                return ResourceManager.GetString("NotEmptyStrokeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        internal static string NothingAtAddress {
            get {
                return ResourceManager.GetString("NothingAtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should be equal.
        /// </summary>
        internal static string PasswordRepeatMismath {
            get {
                return ResourceManager.GetString("PasswordRepeatMismath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        internal static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one lowercase (&apos;a&apos;-&apos;z&apos;).
        /// </summary>
        internal static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one non alphanumeric character.
        /// </summary>
        internal static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;).
        /// </summary>
        internal static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short, it should be at least.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radical.
        /// </summary>
        internal static string Radical {
            get {
                return ResourceManager.GetString("Radical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study is complete.
        /// </summary>
        internal static string StudyIsComplete {
            get {
                return ResourceManager.GetString("StudyIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not exceed .
        /// </summary>
        internal static string ValueTooLong {
            get {
                return ResourceManager.GetString("ValueTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the kun reading of .
        /// </summary>
        internal static string WhatIsKunyomiFor {
            get {
                return ResourceManager.GetString("WhatIsKunyomiFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the meaning of .
        /// </summary>
        internal static string WhatIsMeaningFor {
            get {
                return ResourceManager.GetString("WhatIsMeaningFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the on reading of .
        /// </summary>
        internal static string WhatIsOnyomiFor {
            get {
                return ResourceManager.GetString("WhatIsOnyomiFor", resourceCulture);
            }
        }
    }
}
